export const titleMap = {
  옷장: "closet",
  색상: "color",
  종류: "category",
  패턴: "pattern",
};

export const filterMap = {
  옷장: [],
  색상: [
    "빨간색",
    "주황색",
    "노란색",
    "파란색",
    "남색",
    "보라색",
    "분홍색",
    "갈색",
    "검은색",
    "흰색",
    "회색",
    "베이지색",
  ],
  종류: ["블라우스", "가디건", "코트", "재킷"],
  패턴: ["체크", "도트", "스트라이프", "꽃무늬", "무지", "기타"],
};

export const translate = {
  색상: "color",
  종류: "type",
  패턴: "pattern",
  빨간색: "RED",
  주황색: "ORANGE",
  노란색: "YELLOW",
  파란색: "BLUE",
  남색: "NAVY",
  보라색: "PURPLE",
  분홍색: "PINK",
  갈색: "BROWN",
  검은색: "BLACK",
  흰색: "WHITE",
  회색: "GRAY",
  베이지색: "BEIGE",
  블라우스: "BLOUSE",
  가디건: "CARDIGAN",
  코트: "COAT",
  재킷: "JACKET",
  체크: "CHECK",
  도트: "DOT",
  스트라이프: "STRIPE",
  꽃무늬: "PLANTS",
  무지: "ETC",
  기타: "BLANK",
};
export const filterItems = {
  closet: [],
  color: [
    "RED",
    "ORANGE",
    "YELLOW",
    "GREEN",
    "BLUE",
    "NAVY",
    "PURPLE",
    "PINK",
    "BROWN",
    "BLACK",
    "GRAY",
    "WHITE",
    "BEIGE",
  ],
  category: [
    "BLOUSE",
    "CARDIGAN",
    "COAT",
    "JACKET",
    "JUMPER",
    "SHIRT",
    "SWEATER",
    "TSHIRT",
    "VEST",
    "PANTS",
    "SKIRT",
    "DRESS",
    "JUMPSUITE",
  ],
  pattern: ["CHECK", "DOT", "STRIPE", "PLANTS", "ETC", "BLANK"],
};

export const filterLabels = {
  color: {
    RED: "빨간색",
    ORANGE: "주황색",
    YELLOW: "노란색",
    GREEN: "초록색",
    BLUE: "파란색",
    NAVY: "남색",
    PURPLE: "보라색",
    PINK: "분홍색",
    BROWN: "갈색",
    BLACK: "검은색",
    GRAY: "회색",
    WHITE: "흰색",
    BEIGE: "베이지색",
  },
  category: {
    BLOUSE: "블라우스",
    CARDIGAN: "가디건",
    COAT: "코트",
    JACKET: "재킷",
    JUMPER: "점퍼",
    SHIRT: "셔츠",
    SWEATER: "스웨터",
    TSHIRT: "티셔츠",
    VEST: "조끼",
    PANTS: "바지",
    SKIRT: "치마",
    DRESS: "원피스",
    JUMPSUITE: "점프수트",
  },
  pattern: {
    CHECK: "체크",
    DOT: "도트",
    STRIPE: "스트라이프",
    PLANTS: "꽃무늬",
    ETC: "기타",
    BLANK: "무지",
  },
  season: {
    SPRING: "봄",
    SUMMER: "여름",
    AUTUMN: "가을",
    WINTER: "겨울",
    DEFAULT: "사계절",
  },
};
