export const filterItems = {
  closet: [], // 옷장: []
  color: [
    "RED",
    "ORANGE",
    "YELLOW",
    "GREEN",
    "BLUE",
    "NAVY",
    "PURPLE",
    "PINK",
    "BROWN",
    "BLACK",
    "GRAY",
    "WHITE",
    "BEIGE",
  ],
  category: [
    "BLOUSE",
    "CARDIGAN",
    "COAT",
    "JACKET",
    "JUMPER",
    "SHIRT",
    "SWEATER",
    "T-SHIRT",
    "VEST",
    "PANTS",
    "SKIRT",
    "DRESS",
    "JUMPSUIT",
  ],
  pattern: ["CHECK", "DOT", "STRIPE", "PLANTS", "OTHER", "PLAIN"],
};

export const filterLabels = {
  color: {
    RED: "빨간색",
    ORANGE: "주황색",
    YELLOW: "노란색",
    GREEN: "초록색",
    BLUE: "파란색",
    NAVY: "남색",
    PURPLE: "보라색",
    PINK: "분홍색",
    BROWN: "갈색",
    BLACK: "검은색",
    GRAY: "회색",
    WHITE: "흰색",
    BEIGE: "베이지색",
  },
  category: {
    BLOUSE: "블라우스",
    CARDIGAN: "가디건",
    COAT: "코트",
    JACKET: "재킷",
    JUMPER: "점퍼",
    SHIRT: "셔츠",
    SWEATER: "스웨터",
    TSHIRT: "티셔츠",
    VEST: "조끼",
    PANTS: "바지",
    SKIRT: "치마",
    DRESS: "원피스",
    JUMPSUITE: "점프수트",
  },
  pattern: {
    CHECK: "체크",
    DOT: "도트",
    STRIPE: "스트라이프",
    PLANTS: "꽃무늬",
    ETC: "기타",
    BLANK: "무지",
  },
};
